### ISSUE TITLE
Error message on start

### ISSUE THREAD

**Issue by ankidoc** [julienbordet/MenuPing#19]
![VtUfTNhI](https://user-images.githubusercontent.com/81517565/216967797-5795a14c-c257-4b80-b511-33f6b14e4376.png)

Running MacOS Monterey latest version
M1 Mac Mini 16 Gb

there is nothing in the console.

**Comment by QuiRohn02** [comment]
<img width="258" alt="Schermata 2023-02-07 alle 11 05 16" src="https://user-images.githubusercontent.com/116296915/217214399-676a62d5-de25-4d7f-ae1f-b0e9395c1b92.png">
Same error.
Running on MacOs Monterey 12.4, MacBook Pro M1 8 Gb

**Comment by julienbordet** [comment]
Hi. 

Can you confirm you are on Intel platform ?

Can you check with v0.4.2 that was just released ?
https://github.com/julienbordet/MenuPing/releases/tag/v0.4.2

Julien

**Comment by QuiRohn02** [comment]
> 

Hi, i'm on M1 platform. 
I've just checked v0.4.2 and still give me that error

**Comment by julienbordet** [comment]
Can you please type the following commands in your terminal 

```
$ type -a python
```

from the directory where MenuPing.app is located : 

```
$ otool -L MenuPing.app/Contents/MacOS/MenuPing
```

```
$ ./MenuPing.app/Contents/MacOS/python -V
```

I'm setting up a Monterey VM to try to reproduce the issue

**Comment by QuiRohn02** [comment]
> 

> $ type -a python

 ~ % type -a python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /usr/local/bin/python

> $ otool -L MenuPing.app/Contents/MacOS/MenuPing


 MenuPing.app % otool -L MenuPing.app/Contents/MacOS/MenuPing
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.

> $ ./MenuPing.app/Contents/MacOS/python -V


zsh: no such file or directory: ./MenuPing.app/Contents/MacOS/python

**Comment by voroninman** [comment]
I'm expiriencing the same problem on Sonoma 14.0 Beta (23A5337a).

Here is the log if I try to run the app from the terminal:

```
$ /Applications/MenuPing.app/Contents/MacOS/MenuPing
dlopen(/Applications/MenuPing.app/Contents/Frameworks/libpython3.9.dylib, 0x0001): tried: '/Applications/MenuPing.app/Contents/Frameworks/libpython3.9.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/MenuPing.app/Contents/Frameworks/libpython3.9.dylib' (no such file), '/Applications/MenuPing.app/Contents/Frameworks/libpython3.9.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by julienbordet** [comment]
> I'm expiriencing the same problem on Sonoma 14.0 Beta (23A5337a).
> 
> Here is the log if I try to run the app from the terminal:
> 
> ```
> $ /Applications/MenuPing.app/Contents/MacOS/MenuPing
> dlopen(/Applications/MenuPing.app/Contents/Frameworks/libpython3.9.dylib, 0x0001): tried: '/Applications/MenuPing.app/Contents/Frameworks/libpython3.9.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/MenuPing.app/Contents/Frameworks/libpython3.9.dylib' (no such file), '/Applications/MenuPing.app/Contents/Frameworks/libpython3.9.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
> ```

Hi

Can you confirm you have a M1 platform ?

If so, you probably downloaded the wrong version of MenuPing. Can you try again on the releases page [here](https://github.com/julienbordet/MenuPing/releases) and grab **MenuPing.dmg** and not MenuPing-x86.dmg.

Have a nice day.

**Comment by voroninman** [comment]
> Can you confirm you have a M1 platform ?
> 
> If so, you probably downloaded the wrong version of MenuPing. Can you try again on the releases page [here](https://github.com/julienbordet/MenuPing/releases) and grab **MenuPing.dmg** and not MenuPing-x86.dmg.

You're absolutely right. I have downloaded the wrong version. After installing the correct release, it works like expected. 🙏

**Comment by julienbordet** [comment]
> > Can you confirm you have a M1 platform ?
> > If so, you probably downloaded the wrong version of MenuPing. Can you try again on the releases page [here](https://github.com/julienbordet/MenuPing/releases) and grab **MenuPing.dmg** and not MenuPing-x86.dmg.
> 
> You're absolutely right. I have downloaded the wrong version. After installing the correct release, it works like expected. 🙏

Happy to help !
